name = "Sterculius"
author = "epicgoatcheese and Peter Pop Off"
version = "v0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38cd5300800b6102b883a21e00214ab0c82240cf22ee7c678894318523da7d6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
