name = "Sterculius"
author = "epicgoatcheese and Peter Pop Off"
version = "v0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afac83255cb729be03178b882bdee935e343deedf3efd09d1e8dad2d0f0d5136"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
